title: Nakshatra
email: nakshatra@nitt.edu
description: >- 
  The Official Astronomy and Science Club of NIT Trichy
twitter_username: nakshatra_nitt

plugins:
  - jekyll-seo-tag
  - jekyll-feed

collections_dir: content

exclude: ['docker-compose.yml']

collections:
  pages:
  events: